modLoader="javafml"
loaderVersion="[4,)"
license="${license}"
issueTrackerURL="${sources}/issues"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="${homepage}"
logoFile="assets/gallium/icon.png"
authors="ChooseC, G2F1SH"
description='''${description}'''
displayTest="IGNORE_ALL_VERSION"

[modproperties.gallium]
"sodium:config_api_user"="cn.spectra.gallium.compat.sodium.GalliumSodiumConfig"

[[dependencies.gallium]]
modId="neoforge"
type="required"
versionRange="${neoforge_dependency}"
ordering="NONE"
side="CLIENT"

[[dependencies.gallium]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="gallium-glowoutline.mixins.json"

[[mixins]]
config="gallium-neoforge.mixins.json"
