package cn.spectra.gallium.config;

import cn.spectra.gallium.Gallium;
import cn.spectra.gallium.glowoutline.GlowOutlineConfig;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import net.fabricmc.loader.api.FabricLoader;

import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;

public final class GalliumConfigIO {

    private static final int CURRENT_VERSION = 1;
    private static final String FILE_NAME = "gallium.json";
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();

    private GalliumConfigIO() {}

    private static Path configPath() {
        return FabricLoader.getInstance().getConfigDir().resolve(FILE_NAME);
    }

    public static void load() {
        Path path = configPath();
        if (!Files.exists(path)) {
            save();
            return;
        }
        try (Reader reader = Files.newBufferedReader(path, StandardCharsets.UTF_8)) {
            JsonObject root = JsonParser.parseReader(reader).getAsJsonObject();
            applyToRuntime(root);
        } catch (Exception e) {
            Gallium.LOGGER.warn("Failed to load {}, using defaults: {}", FILE_NAME, e.toString());
        }
    }

    public static void save() {
        Path path = configPath();
        Path tmp = path.resolveSibling(FILE_NAME + ".tmp");
        try {
            Files.createDirectories(path.getParent());
            JsonObject root = serializeRuntime();
            try (Writer writer = Files.newBufferedWriter(tmp, StandardCharsets.UTF_8)) {
                GSON.toJson(root, writer);
            }
            try {
                Files.move(tmp, path, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException atomicFail) {
                Files.move(tmp, path, StandardCopyOption.REPLACE_EXISTING);
            }
        } catch (Exception e) {
            Gallium.LOGGER.warn("Failed to save {}: {}", FILE_NAME, e.toString());
            try { Files.deleteIfExists(tmp); } catch (IOException ignored) {}
        }
    }

    private static JsonObject serializeRuntime() {
        JsonObject root = new JsonObject();
        root.addProperty("_comment", "Generated by Gallium. Edit through in-game settings.");
        root.addProperty("config_version", CURRENT_VERSION);
        root.addProperty("enabled", GlowOutlineConfig.isEnabled());

        JsonObject targets = new JsonObject();
        targets.addProperty("first_person", GlowOutlineConfig.isFirstPerson());
        targets.addProperty("third_person", GlowOutlineConfig.isThirdPerson());
        targets.addProperty("other_entities", GlowOutlineConfig.isOtherEntities());
        targets.addProperty("dropped_items", GlowOutlineConfig.isDroppedItems());
        targets.addProperty("armor", GlowOutlineConfig.isArmor());
        targets.addProperty("gui", GlowOutlineConfig.isGui());
        root.add("render_targets", targets);
        return root;
    }

    private static void applyToRuntime(JsonObject root) {
        if (root.has("enabled")) GlowOutlineConfig.setEnabled(root.get("enabled").getAsBoolean());

        if (root.has("render_targets") && root.get("render_targets").isJsonObject()) {
            JsonObject t = root.getAsJsonObject("render_targets");
            if (t.has("first_person"))    GlowOutlineConfig.setFirstPerson(t.get("first_person").getAsBoolean());
            if (t.has("third_person"))    GlowOutlineConfig.setThirdPerson(t.get("third_person").getAsBoolean());
            if (t.has("other_entities"))  GlowOutlineConfig.setOtherEntities(t.get("other_entities").getAsBoolean());
            if (t.has("dropped_items"))   GlowOutlineConfig.setDroppedItems(t.get("dropped_items").getAsBoolean());
            if (t.has("armor"))           GlowOutlineConfig.setArmor(t.get("armor").getAsBoolean());
            if (t.has("gui"))             GlowOutlineConfig.setGui(t.get("gui").getAsBoolean());
        }
    }
}
