package cn.spectra.gallium.config;

import cn.spectra.gallium.Gallium;
import cn.spectra.gallium.glowoutline.GlowOutlineConfig;
import cn.spectra.gallium.glowoutline.GlowOutlineConfig.Group;
import cn.spectra.gallium.glowoutline.GlowOutlineConfig.Toggle;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import net.fabricmc.loader.api.FabricLoader;

import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;

public final class GalliumConfigIO {

    private static final int CURRENT_VERSION = 1;
    private static final String FILE_NAME = "gallium.json";
    private static final String RENDER_TARGETS_KEY = "render_targets";
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();

    private GalliumConfigIO() {}

    private static Path configPath() {
        return FabricLoader.getInstance().getConfigDir().resolve(FILE_NAME);
    }

    public static void load() {
        Path path = configPath();
        if (!Files.exists(path)) {
            save();
            return;
        }
        try (Reader reader = Files.newBufferedReader(path, StandardCharsets.UTF_8)) {
            JsonObject root = JsonParser.parseReader(reader).getAsJsonObject();
            applyToRuntime(root);
        } catch (Exception e) {
            Gallium.LOGGER.warn("Failed to load {}, using defaults: {}", FILE_NAME, e.toString());
        }
    }

    public static void save() {
        Path path = configPath();
        Path tmp = path.resolveSibling(FILE_NAME + ".tmp");
        try {
            Files.createDirectories(path.getParent());
            JsonObject root = serializeRuntime();
            try (Writer writer = Files.newBufferedWriter(tmp, StandardCharsets.UTF_8)) {
                GSON.toJson(root, writer);
            }
            try {
                Files.move(tmp, path, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException atomicFail) {
                Files.move(tmp, path, StandardCopyOption.REPLACE_EXISTING);
            }
        } catch (Exception e) {
            Gallium.LOGGER.warn("Failed to save {}: {}", FILE_NAME, e.toString());
            try { Files.deleteIfExists(tmp); } catch (IOException ignored) {}
        }
    }

    private static JsonObject serializeRuntime() {
        JsonObject root = new JsonObject();
        root.addProperty("_comment", "Generated by Gallium. Edit through in-game settings.");
        root.addProperty("config_version", CURRENT_VERSION);

        JsonObject targets = new JsonObject();
        for (Toggle t : Toggle.values()) {
            if (t.group() == Group.GLOBAL) {
                root.addProperty(t.jsonKey(), t.get());
            } else {
                targets.addProperty(t.jsonKey(), t.get());
            }
        }
        root.add(RENDER_TARGETS_KEY, targets);
        return root;
    }

    private static void applyToRuntime(JsonObject root) {
        JsonObject targets = root.has(RENDER_TARGETS_KEY) && root.get(RENDER_TARGETS_KEY).isJsonObject()
                ? root.getAsJsonObject(RENDER_TARGETS_KEY) : null;
        for (Toggle t : Toggle.values()) {
            JsonObject src = t.group() == Group.GLOBAL ? root : targets;
            if (src != null && src.has(t.jsonKey())) {
                t.set(src.get(t.jsonKey()).getAsBoolean());
            }
        }
    }
}
